apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: metadata
  title: Metadata
  description: Statistics Norway's metadata system
  tags:
    - metadata
  links:
    - url: https://manual.dapla.ssb.no/statistikkere/metadata.html
      title: Dapla Manual
      icon: techdocs
    - url: https://statistics-norway.atlassian.net/wiki/x/RACo1w
      title: Team Metadata Confluence
      icon: techdocs
    - url: https://ssb-norge.slack.com/archives/C069BAVNGA0
      title: Team Metadata Slack (send us a message :) )
      icon: chat
spec:
  owner: dapla-metadata-developers
  domain: dapla
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: metadata-mongodb
  title: Metadata MongoDB
  description: MongoDB cluster for the Metadata system
  tags:
    - database
    - mongodb
    - metadata
spec:
  type: database
  system: metadata
  owner: dapla-metadata-developers
  lifecycle: experimental
